version: "3.6"
x-daemon: &defaults
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"
  networks:
    - baship
services:
  app:
    <<: *defaults
    build:
      context: ./app
      dockerfile: Dockerfile
    expose:
      - 80
    environment:
      CONTAINER_ENV: "${APP_ENV}"
      XDEBUG_HOST: "${XDEBUG_HOST}"
      WWWUSER: "${WWWUSER}"
      WWWGROUP: "${WWWGROUP}"
      VIRTUAL_HOST: "${VIRTUAL_HOST}"
    volumes:
      - ..:/var/www:delegated
  node:
    <<: *defaults
    build:
      context: ./node
      dockerfile: Dockerfile
      args:
        uid: "${WWWUSER}"
        gid: "${WWWGROUP}"
    user: node
    volumes:
      - ..:/var/www:delegated
  mysql:
    <<: *defaults
    image: mariadb:10.5
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - bashipmysql:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
      # - ./mysql/logs:/var/log/mysql
      - ./mysql/backup:/docker-entrypoint-initdb.d
  redis:
    <<: *defaults
    image: redis:alpine
    volumes:
      - bashipredis:/data
networks:
  baship:
    driver: "bridge"
volumes:
  bashipmysql:
    driver: "local"
  bashipredis:
    driver: "local"